### ISSUE TITLE
予約一覧が多くなった場合のスクロール対応

### ISSUE THREAD

**Issue by ak-kitsuda** [ak-kitsuda/cursor-demo#1]
## 概要
現在の予約一覧表示では、予約件数が多くなると画面が縦に長くなり、ユーザー体験が低下します。予約一覧部分を固定高さのコンテナにしてスクロール可能にすることで改善します。

## 現状の問題点
- 予約が増えると画面が縦に伸びてしまう
- 多数の予約がある場合、他の機能へのアクセスが困難になる

## 提案する変更
1. `reservationsList` コンテナに固定高さを設定
2. オーバーフローした内容をスクロール表示できるようにする
3. スクロールバーのスタイルをアプリケーションの外観に合わせる

## 実装内容
以下のような CSS の追加を検討：

```css
#reservationsList {
  max-height: 400px; /* または適切な高さ */
  overflow-y: auto;
  border: 1px solid #e0e0e0;
  border-radius: 5px;
  padding: 10px;
}
```

## 期待される結果
- 予約数に関わらず予約一覧部分が一定の高さで表示される
- ユーザーは必要に応じてスクロールして全予約を確認できる
- 画面全体のレイアウトが安定し、ユーザー体験が向上する
